[book]
authors = ["Kai Müller"]
language = "en"
multilingual = false
src = "src"
title = ""

[build]
build-dir = "docs"
create-missing = false

[output.html]
additional-css = ["theme/custom.css", "theme/tabbed-code-blocks.css"]
additional-js = ["theme/tabbed-code-blocks.js"]
no-section-label = true
